const data = {
    products: [
        {
            _id: '1',
            name: 'ASUS Dual GeForce RTX 3070',
            category: 'Graphics Card',
            image: './images/RTX3070.jpg',
            price: 1000,
            brand: 'Asus',
            rating: 4.5,
            numReviews: 10,
            description: 'Chipset: NVIDIA GeForce RTX 3070',
        },
        {
            _id: '2',
            name: 'MSI Gaming GeForce RTX 3070',
            category: 'Graphics Card',
            image: './images/RTX3070(1).jpg',
            price: 990.38,
            brand: 'MSI',
            rating: 5.0,
            numReviews: 10,
            description: 'Chipset: NVIDIA GeForce RTX 3070',
        },
        {
            _id: '3',
            name: 'ZOTAC Gaming GeForce RTX 3090 Trinity',
            category: 'Graphics Card',
            image: './images/RTX3090.jpg',
            price: 2500,
            brand: 'Zotac',
            rating: 3.0,
            numReviews: 10,
            description: 'Chipset: NVIDIA GeForce RTX 3090',
        },
        {
            _id: '4',
            name: 'ASUS GeForce RTX 2060 Overclocked',
            category: 'Graphics Card',
            image: './images/RTX2060.jpg',
            price: 680.50,
            brand: 'Asus',
            rating: 4.5,
            numReviews: 10,
            description: 'Chipset: NVIDIA GeForce RTX 2060',
        },
        {
            _id: '5',
            name: 'EVGA GeForce RTX 2080 Ti',
            category: 'Graphics Card',
            image: './images/RTX2080ti.jpg',
            price: 1449.79,
            brand: 'EVGA',
            rating: 4.0,
            numReviews: 10,
            description: 'Chipset: NVIDIA GeForce RTX 2080 Ti',
        },
        {
            _id: '6',
            name: 'ZOTAC Gaming GeForce RTX 3060 Twin Edge',
            category: 'Graphics Card',
            image: './images/RTX3060.jpg',
            price: 800,
            brand: 'Zotac',
            rating: 4.0,
            numReviews: 10,
            description: 'Chipset: NVIDIA GeForce RTX 3060',
        },
    ],
};

export default data;